# Multiple Linear Regression

## Importing the libraries

In [245]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [246]:
dataset = pd.read_csv('Crop_recommendation.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [247]:
print(X)

[[ 90.    42.    43.   ...  82.     6.5  202.94]
 [ 85.    58.    41.   ...  80.32   7.04 226.66]
 [ 60.    55.    44.   ...  82.32   7.84 263.96]
 ...
 [118.    33.    30.   ...  67.23   6.36 173.32]
 [117.    32.    34.   ...  52.13   6.76 127.18]
 [104.    18.    30.   ...  60.4    6.78 140.94]]


In [248]:
print(y)

['rice' 'rice' 'rice' ... 'coffee' 'coffee' 'coffee']


## Encoding categorical data

In [249]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
y = le.fit_transform(y)
i = le.inverse_transform(y)

In [250]:
print(y)

[20 20 20 ...  5  5  5]


In [251]:
print(i)

['rice' 'rice' 'rice' ... 'coffee' 'coffee' 'coffee']


## Splitting the dataset into the Training set and Test set

In [252]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [253]:
print(X_train)

[[ 27.   120.   200.   ...  90.75   6.11 116.7 ]
 [ 81.    36.    38.   ...  87.98   6.33 150.32]
 [ 90.    59.    35.   ...  89.86   7.1  175.17]
 ...
 [ 35.    64.    15.   ...  63.54   6.5   69.53]
 [ 39.    65.    23.   ...  69.13   7.69  41.03]
 [ 14.    22.     9.   ...  91.14   6.54 112.51]]


In [254]:
print(y_train)

[ 0  8  8 ...  2 10 16]


## Training the Multiple Linear Regression model on the Training set

In [255]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X, y)

RandomForestRegressor(n_estimators=10, random_state=0)

## Predicting the Test set results

In [256]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[21.  21. ]
 [21.  21. ]
 [ 7.   7. ]
 [ 3.   3. ]
 [ 2.   2. ]
 [20.  20. ]
 [13.5 13. ]
 [ 9.   9. ]
 [15.  15. ]
 [ 1.   1. ]
 [13.  13. ]
 [ 5.   5. ]
 [10.  10. ]
 [14.  14. ]
 [12.  12. ]
 [ 0.   0. ]
 [ 5.   5. ]
 [10.  10. ]
 [ 5.   5. ]
 [12.  12. ]
 [ 4.   4. ]
 [ 2.   2. ]
 [10.8  9. ]
 [ 9.2  8. ]
 [ 6.   6. ]
 [ 5.   5. ]
 [10.  10. ]
 [16.  16. ]
 [13.  13. ]
 [ 8.4  9. ]
 [19.  19. ]
 [20.  20. ]
 [11.  11. ]
 [15.  15. ]
 [ 4.   4. ]
 [ 6.5  6. ]
 [12.  12. ]
 [12.  12. ]
 [21.  21. ]
 [12.4 13. ]
 [11.  11. ]
 [ 2.   2. ]
 [18.  18. ]
 [21.  21. ]
 [18.  18. ]
 [14.  14. ]
 [ 9.   9. ]
 [ 9.   9. ]
 [ 6.   6. ]
 [14.  14. ]
 [13.  13. ]
 [ 2.   2. ]
 [ 0.   0. ]
 [15.  15. ]
 [18.  18. ]
 [ 1.   1. ]
 [17.  17. ]
 [12.  12. ]
 [10.  10. ]
 [ 6.   6. ]
 [16.  16. ]
 [14.  14. ]
 [21.  21. ]
 [20.  20. ]
 [15.  15. ]
 [ 0.   0. ]
 [ 7.   7. ]
 [ 5.   5. ]
 [ 0.   0. ]
 [16.  16. ]
 [ 4.   4. ]
 [19.  19. ]
 [ 9.   9. ]
 [10.7 11. ]
 [ 7.   7. ]
 [13.  13. ]
 [ 3.   3. ]

In [257]:
print(y_test)

[21 21  7  3  2 20 13  9 15  1 13  5 10 14 12  0  5 10  5 12  4  2  9  8
  6  5 10 16 13  9 19 20 11 15  4  6 12 12 21 13 11  2 18 21 18 14  9  9
  6 14 13  2  0 15 18  1 17 12 10  6 16 14 21 20 15  0  7  5  0 16  4 19
  9 11  7 13  3 11  8 12 20  2 21 21 15  6 11 10 13 17  2  8 14  7 14 11
  5  8 10  3 16  8 14  1  1 20 21  5 18 15 15 12  5  7 16 19 14 10 11  8
 19 10 16  3  3  2 19 16  3 17 13 13 15 14 11 14  4 19 16  2  2  7  0  5
  3  0  8 12 21 17 16  4 13  1 19  3 21  2  0  8 10 18  8  9  9 15 20 15
  1 16 18  0 13  4  6 14  9 19 17 16 20 17 17 18  9  1  4 18 20 17 11  8
 13 20 11  5 18  4  3 12  4 19 11 13 13 16 15 11 18  1  3  2 18 16 13 14
 12 17 15 19 20 20  2 17  2  5 11  5 16 20 13 14 16  9 19  4 12 14  6 20
  3 14  0 18  2 20 21  2 19 16 11  7  3 18  8 17 19  5 12 13  8 21 19 20
  7  4  8 10  3  5  5 17 19 11 20  3 18 16 19 18  4  9 19 15 13 12 10  1
  2 12  9 12  6 14 17  7  7 18 17  8 20  3 15  5 21 20  8 17  7 15  2 13
 13  3  2 12  1 12 19  8 16 15  3 10  6 17  7  9 10

In [258]:
y_pred = np.array(y_pred)
y_pred = np.asarray(y_pred, dtype = 'int')

print(y_pred[1])

21


## Accuracy Score

In [259]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred) * 100)

93.18181818181817


In [260]:
y_pred = le.inverse_transform(y_pred)
print(y_pred)

['watermelon' 'watermelon' 'grapes' 'chickpea' 'blackgram' 'rice'
 'mothbeans' 'kidneybeans' 'muskmelon' 'banana' 'mothbeans' 'coffee'
 'lentil' 'mungbean' 'mango' 'apple' 'coffee' 'lentil' 'coffee' 'mango'
 'coconut' 'blackgram' 'lentil' 'kidneybeans' 'cotton' 'coffee' 'lentil'
 'orange' 'mothbeans' 'jute' 'pomegranate' 'rice' 'maize' 'muskmelon'
 'coconut' 'cotton' 'mango' 'mango' 'watermelon' 'mango' 'maize'
 'blackgram' 'pigeonpeas' 'watermelon' 'pigeonpeas' 'mungbean'
 'kidneybeans' 'kidneybeans' 'cotton' 'mungbean' 'mothbeans' 'blackgram'
 'apple' 'muskmelon' 'pigeonpeas' 'banana' 'papaya' 'mango' 'lentil'
 'cotton' 'orange' 'mungbean' 'watermelon' 'rice' 'muskmelon' 'apple'
 'grapes' 'coffee' 'apple' 'orange' 'coconut' 'pomegranate' 'kidneybeans'
 'lentil' 'grapes' 'mothbeans' 'chickpea' 'maize' 'jute' 'mango' 'rice'
 'coconut' 'watermelon' 'watermelon' 'muskmelon' 'cotton' 'kidneybeans'
 'lentil' 'mango' 'papaya' 'blackgram' 'jute' 'mungbean' 'grapes'
 'mungbean' 'lentil' 'coff

## Single Predicting


In [261]:
s_pred = regressor.predict([[90,42,43,20.87974371,82.00274423,6.502985292000001,202.9355362]])
# print(s_pred[0]);
s_pred = le.inverse_transform([int(s_pred[0])])
print(s_pred[0])

rice
